allow-shears: true
allow-saplingbreak-with-perm: false
allow-mushroombreak-with-perm: false
enable-sapling-interval-growth: false
enable-mushroom-interval-growth: true
sapling-growth-interval: 180
mushroom-growth-interval: 180
sapling-growth-chance: 25
mushroom-growth-chance: 25
strings:
  commandNonExistant: '&cThat command does not exist.'
  cannotBreakMushroom: '&8[&6Tree Farm&8] &cYou need to let the mushrooms grow!'
  cannotBreakSapling: '&8[&6Tree Farm&8] &cYou need to let the saplings grow!'
  help:
  - '&6[WGTreeFarmFlag] &7Commands:'
  - '&cUsage: /wgtreefarmflag <command>'
  - '&chelp  &7View a list of all WGTreeFarmFlag commands.'
  - '&creload  &7Reload the plugin.'
  info:
  - '&6[WGTreeFarmFlag] &7Version %version%'
  - '&6[WGTreeFarmFlag] &7By S_Ryan'
  noPermission: '&cYou do not have permission for that command.'
  reloaded: '&6[WGTreeFarmFlag] &7Successfully reloaded.'
debug: false
debug-level: 2
debug-header: '&6WGTreeFarmFlag->&cdebug&6> &r'
config-version: 2