name: WGTreeFarmFlag
version: S_Ryan
main: net.src_dev.wgtreefarmflag.WGTreeFarmFlag
description: Adds a custom tree-farm flag to WorldGuard.
author: S_Ryan
depend: [WorldGuard,WGCustomFlags]
softdepend: [Multiworld]
commands:
  wgtreefarmflag:
    description: Base command for all WGTreeFarmFlag commands.
    usage: /wgtreefarmflag <command>
    aliases: []